version: '3'
services:
  db:
    image: library/mysql:8.0.24
    container_name: doggie
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    restart: always
  app:
    image: library/usermanage
    container_name: app
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    restart: always
    links:
      - db
